# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  build:
    cmds:
      - ./gradlew build
      - cp my-tracker/MyTracker.gdap my-tracker/build/outputs/aar/MyTracker.gdap

  example:
    deps: [build]
    cmds:
      - cp my-tracker/build/outputs/aar/mytracker-debug.aar ./example/android/plugins/mytracker-release.aar
      - cp my-tracker/build/outputs/aar/MyTracker.gdap ./example/android/plugins/MyTracker.gdap